#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
  systemctl enable ec-systemcore.service || true
  systemctl restart ec-systemcore.service || systemctl start ec-systemcore.service || true
fi

exit 0
