#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop ec-systemcore.service || true
  systemctl disable ec-systemcore.service || true
  systemctl daemon-reload || true
fi

exit 0
